version: '3'
services:
  discovery:
    image: eureka-docker
    ports:
      - 8761:8761


  korisnik:
    image: korisnik-service-docker
    ports:
      - 8082:8082
    depends_on:
      - discovery
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka

  zivotinja-db:
    image: "postgres"
    container_name: zivotinja-db
    ports:
      - 5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: zivotinja-service
      POSTEGRES_USER: postgres
      POSTEGRES_PASSWORD: admin


  zivotinja-service:
    image: zivotinja-service-docker
    container_name: zivotinja-service
    ports:
      - 8080:8080
    depends_on:
      - discovery
      - zivotinja-db
    environment:
      - DATABASE_HOST=zivotinja-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=zivotinja-service
      - DATABASE_PORT=5432

  frontend:
    image: frontend-docker
    ports:
      - 9002:80


