version: '3'
networks:
  petfriend:
    driver: bridge

services:
  discovery:
    image: eureka-docker
    ports:
      - 8761:8761
    networks:
      - petfriend


  korisnik:
    image: korisnik-service-docker
    ports:
      - 8082:8082
    depends_on:
      - discovery
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    networks:
      - petfriend

  zivotinja-db:
    image: "postgres"
    container_name: zivotinja-db
    ports:
      - 5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: zivotinja-service
      POSTEGRES_USER: postgres
      POSTEGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - petfriend


  zivotinja-service:
    image: zivotinja-service-docker
    ports:
      - 8080:8080
    depends_on:
      - discovery
      - zivotinja-db
    environment:
      - DATABASE_HOST=zivotinja-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=zivotinja-service
      - DATABASE_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://zivotinja-db:5432/zivotinja-service
    networks:
      - petfriend

  frontend:
    image: frontend-docker
    ports:
      - 9002:80
    networks:
      - petfriend


